export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_UPDATED= "USER_UPDATED";
export const USER_DETAILS= "USER_DETAILS";

export const BOOKS_FETCHED = "BOOKS_FETCHED";
export const BOOK_CREATED = "BOOK_CREATED";
export const BOOK_CLEARED = "BOOK_CLEARED";

export const WORKOUTS_FETCHED = "WORKOUTS_FETCHED";
export const WORKOUTS_CLEARED = "WORKOUTS_CLEARED";
export const WORKOUT_CREATED = "WORKOUT_CREATED";
export const WORKOUT_DELETED = "WORKOUT_DELETED";
export const WORKOUT_MODIFIED = "WORKOUT_MODIFIED";

export const EXERCISES_FETCHED = "EXERCISE_FETCHED";
export const EXERCISES_CLEARED = "EXERCISE_CLEARED";
export const EXERCISE_CREATED = "EXERCISE_CREATED";
export const EXERCISE_DELETED = "EXERCISE_DELETED";
export const EXERCISE_MODIFIED = "EXERCISE_MODIFIED";

export const ORGANISATIONS_FETCHED= "ORGANISATION_FETCHED";
export const ORGANISATION_CREATED= "ORGANISATION_CREATED";
export const ORGANISATION_MODIFIED= "ORGANISATION_MODIFIED";
export const ORGANISATION_DELETED= "ORGANISATION_DELETED";
export const ORGANISATIONS_CLEARED= "ORGANISATIONS_CLEARED";

export const TEAMS_FETCHED= "TEAMS_FETCHED";
export const TEAM_CREATED= "TEAM_CREATED";
export const TEAM_MODIFIED= "TEAM_MODIFIED";
export const TEAM_DELETED= "TEAM_DELETED";
export const TEAMS_CLEARED= "TEAMS_CLEARED";
