export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const BOOKS_FETCHED = "BOOKS_FETCHED";
export const BOOK_CREATED = "BOOK_CREATED";
export const BOOK_CLEARED = "BOOK_CLEARED";

export const WORKOUTS_FETCHED = "WORKOUTS_FETCHED";
export const WORKOUTS_CLEARED = "WORKOUTS_CLEARED";
export const WORKOUT_CREATED = "WORKOUT_CREATED";
export const WORKOUT_DELETED = "WORKOUT_DELETED";
export const WORKOUT_MODIFIED = "WORKOUT_MODIFIED";
